crops_dic = {
	
        'rice-sc-name' : """Oryza Sativa""",
        'rice-desc' : """The cultivated rice plant is an annual grass and grows to about 1.2 metres (4 feet) in height. The leaves are long and flattened and are borne on hollow stems. The fibrous root system is often broad and spreading. The panicle, or inflorescence (flower cluster), is made up of spikelets bearing flowers that produce the fruit, or grain. Varieties differ greatly in the length, shape, and weight of the panicle and the overall productivity of a given plant.""",
        'rice-climate': """Rice crop needs a hot and humid climate. It is best suited to regions which have high humidity, prolonged sunshine and an assured supply of water. The average temperature required throughout the life period of the crop ranges from 21 to 37º C. Maximum temp which the crop can tolerate 400 to 420º C.""",
        'rice-cult': """Many methods of rice cultivation are practised in India. In Broadcasting method, Seeds are sown broadcast by hand. This method is practised in those areas which are comparatively dry and less fertile and do not have much labour to work in the fields. It is the easiest method requiring minimum input but its yields are also minimum. In ploughing method, ploughing of land and sowing of seeds is done by two persons. This method is mostly confined to peninsular India. In transplantation method, eeds are sown in nursery and seedlings are prepared. After 4-5 weeks the seedlings are uprooted and planted in the field which has already been prepared for the purpose. The entire process is done by hand.""",
	

        'apple-sc-name': """Malus domestica""",
        'apple-desc': """The apple is a tree and its pomaceous fruit, of the species Malus domestica in the rose family Rosaceae. It is one of the most widely cultivated tree fruits. It is a small deciduous tree reaching 5-12 m tall, with a broad, often densely twiggy crown. The leaves are alternately arranged, simple oval with an acute tip and serrated margin, slightly downy below, 5-12 cm long and 3-6 cm broad on a 2-5 cm petiole. The flowers are produced in spring with the leaves, white, usually tinged pink at first, 2.5-3.5 cm diameter, with five petals. The fruit matures in autumn, and is typically 5-9 cm diameter (rarely up to 15 cm). The centre of the fruit contains five carpels arranged star-like, each carpel containing one or two (rarely three) seeds.""",
        'apple-cult': """The planting distance varies according to variety and the fertility level of the soil. The main consideration in planting trees is planting of sufficient pollinators to ensure effective pollination. Usually one pollinator tree is needed for two to three large trees planted at 10 m distance or one row pollinator for two rows of main cultivar. For high density planting the pollinator tree is planted after every sixth tree in a row. The most widely used planting system is the square system. In this system, the pollinators are planted after every sixth or ninth tree. The other popular system of planting is the rectangular system. In hilly areas the apple orchards are established by planting the trees on the contours so as to prevent soil erosion and reduce run off. The average number of plants in an area of one ha. can range between 200 to 1250. Four different categories of planting density are followed viz. low (less than 250 plants/ha.), moderate (250-500 plants/ha.), high (500-1250 plants/ha.) and ultra high density (more than 1250 plants /ha.). The combination of rootstock and scion variety determines the plant spacing and planting density/unit area.""",
        'apple-climate': """The apple is a tree and its pomaceous fruit, of the species Malus domestica in the rose family Rosaceae. It is one of the most widely cultivated tree fruits. It is a small deciduous tree reaching 5-12 m tall, with a broad, often densely twiggy crown. The leaves are alternately arranged, simple oval with an acute tip and serrated margin, slightly downy below, 5-12 cm long and 3-6 cm broad on a 2-5 cm petiole. The flowers are produced in spring with the leaves, white, usually tinged pink at first, 2.5-3.5 cm diameter, with five petals. The fruit matures in autumn, and is typically 5-9 cm diameter (rarely up to 15 cm). The centre of the fruit contains five carpels arranged star-like, each carpel containing one or two (rarely three) seeds.""",

        
        'blackgram-sc-name': """Vigna mungo""",
        'blackgram-desc': """Vigna mungo, the black gram, or black matpe is a bean grown in South Asia. Black gram originated in South Asia, where it has been in cultivation from ancient times and is one of the most highly prized pulses of India. It is very widely used in Indian cuisine. In India the black gram is one of the important pulses grown in both Kharif and Rabi seasons. This crop is extensively grown in southern part of India, northern part of Bangladesh and Nepal.It is an erect, suberect or trailing, densely hairy, annual bush. The tap root produces a branched root system with smooth, rounded nodules. The pods are narrow, cylindrical and up to six cm long. The plant grows 30–100 cm with large hairy leaves and 4–6 cm seed pods.While the urad dal was, along with the mung bean, originally placed in Phaseolus, it has since been transferred to Vigna.""",
        'blackgram-cult': """The land should be prepared by 2­-3 plowing, cross plowing with laddering. <br><br> <b> Method of sowing: </b> <br> Broadcasting and line sowing can be done. For line sowing, row to row distance 30 cm. Broadcasting can be done in Kharif season. Seeds should not be sown more than 5 to 6 cm in depth. <br><br> <b>Seed Rate:</b> 35-­40 kg/ha. <br><br> <b>Seed treatment:</b> Seed should be treated with thiram @ 2.5 g / kg seed.<br> It should be treated with rhizobium culture for atmospheric N fixation. </h4>
        """,
        'blackgram-climate': """Gram is the most important of all the pulses and accounts for 37 per cent of the production and 28.28 per cent of the total area of pulses in India. It can be grown in a wide range of chmatic conditions but it prefers mild cool and comparatively dry climate with 20°-25°C temperature and 40-50 cm rainfall.""",


        'chickpea-sc-name' : """Cicer arietinum""",
        'chickpea-desc' : """ Chickpeas are bushy 60-cm (2-foot) plants that bear feathery pinnately compound leaves. The small white or reddish flowers often have distinctive veins in blue or purple and are usually self-pollinated. The yellow-brown or dark green beans are borne one or two to a pod. There are large- and small-seeded varieties.""",
        'chickpea-cult' : """ Chickpeas should be planted in full sun. Chickpeas will grow in partial shade but the yield will be reduced. Grow chickpeas in loose, well-drained soil rich in organic matter. Add aged compost to planting beds in advance of planting.Avoid planting chickpeas where green manures have just grown or in soil high in nitrogen; this will result in green leafy growth, not seed production. Add potassium and phosphorus to the soil.""",
        'chickpea-climate': """ Chickpea is sensitive to high (maximum daily temperature >35°C) as well as low (mean of maximum and minimum daily temperatures <15°C) temperatures at the reproductive stage. Both extremes of temperatures lead to flower drop and reduced pod set.""",


        'coconut-sc-name' : """Cocos nucifera""",
        'coconut-desc' : """A single coconut palm may yield 100 coconuts annually, and each fruit requires a year to fully ripen. Mature coconuts, ovoid or ellipsoid in shape, 300–450 mm (12–18 inches) in length and 150–200 mm (6–8 inches) in diameter, have a thick fibrous husk surrounding the familiar single-seeded nut of commerce. A hard shell encloses the insignificant embryo with its abundant endosperm, composed of both meat and liquid. Coconut fruits float readily and have been dispersed widely by ocean currents and by humans throughout the tropics.""",
        'coconut-cult' : """Time of planting at Main field - Planting may be done from April, May to Sept, October according to the land condition. Early planted seedlings get established during monsoon period. Spacing - In square system, planting distance should be 8mx8m. 156 seedlings can be planted in 1 ha. area i.e. 21 plants can be accommodated in a bigha of land. Higher spacing is always better for inter/ mixed cropping.Size of the pit - Size of the pit may be of 1mx1mx1m. In hard soil, size can be increased to 1.2mx1.2mx1.2m.Pit Mixtures and filling of pits - This can be made by mixing top soil, 500g Rock Phosphate/ S.S.P. 50 kg dry cowdung/compost, 100g 10% sevidol. In hard soil, 1 kg salt may be given at the bottom of the pit for loosening the soil. After planting a bund may be made around the pit for preventing run off water.""",
        'coconut-climate' : """ Coconut is essentially a tropical plant but has been found to grow under varying agro climatic conditions. The mean annual temperature for optimum growth and maximum yield is stated to be 270C with a diurnal variation of 60C to 70C and relative humidity more than 60 %.""",
        

        'coffee-sc-name' : """Coffea""",
        'coffee-desc' : """Members of the genus Coffea are evergreen shrubs or small trees and often inhabit the understory of tropical forests. The elliptical waxy leaves are borne oppositely along the stems and often feature prominent venation. Many species have a characteristic growth habit in which the upright trunks branch horizontally and may then repeat the pattern on secondary and tertiary branches. The small fragrant white or pink flowers frequently open after a dry period and may last only a few days. The fruit, known as a “coffee cherry,” is a one- or two-seeded drupe and can be red, purple, yellow, orange, blue, or black when mature, depending on the species. The “coffee beans” are the rounded oblong seeds, each with a flat face marked by a lengthwise groove.""",
        'coffee-cult' : """Coffee beans are actually seeds. It’s only after they have been dried, roasted and ground that they can be used to brew the humble zip. If unprocessed coffee seeds are planted, they can germinate and grow into coffee plants. The seeds are normally planted in large shaded beds. After sprouting, the young seedlings are left to grow for a few days before moving them to individual pots with carefully formulated soils for optimal growth. The potted seedlings are shaded from the scorching sun and watered frequently until they’re vigorous enough to be moved to their permanent growing place. Planting is best done during the rainy season to ensure the soil will remain moist as the roots get firmly established.""",
        'coffee-climate' : """Coffee requires an average temperature of 15℃ to 28℃ . Growth of the coffee plants is very rapid during the hot rainy season and during the cool dry season the berries get ripened and ready to be plucked. Bright sunshine and warm weather are necessary for harvesting.""",


        'cotton-sc-name' : """Gossypium herbaceum""",
        'cotton-desc' : """ Cotton, one of the world’s leading agricultural crops, is plentiful and economically produced, making cotton products relatively inexpensive. The fibres can be made into a wide variety of fabrics ranging from lightweight voiles and laces to heavy sailcloths and thick-piled velveteens, suitable for a great variety of wearing apparel, home furnishings, and industrial uses. Cotton fabrics can be extremely durable and resistant to abrasion. Cotton accepts many dyes, is usually washable, and can be ironed at relatively high temperatures. It is comfortable to wear because it absorbs and releases moisture quickly.""",
        'cotton-cult' : """ Sowing: The seeds are sown by broadcast method or by drills. Harvesting: The crop is harvested in October when the cotton balls ripen and burst into white, fluffy and shiny balls of fibre.  Processing: After the cotton has been picked, it is ginned. The seeds maybe crushed to yield oil. The cotton fibre is baled for transport to the manufacturing regions. The fibres are washed and then combed to form a rope-like mass of fibres known as sliver. The sliver is fed to the spindles and spun to make cotton yarn.""",
        'cotton-climate' : """Cotton is a tropical crop and it is raised in India as a Kharif crop. Cotton requires uniformly high temperature between 21 degree Celsius and 30 degree Celsius. During October, the day temperature should be above 26 degree Celsius which helps the ripening and bursting of cotton balls under the sunny skies.""",


        'jute-sc-name' : """Corchorus""",
        'jute-desc' : """Jute is a long, soft, shiny bast fiber that can be spun into coarse, strong threads. It is produced from flowering plants in the genus Corchorus, which is in the mallow family Malvaceae. The primary source of the fiber is Corchorus olitorius, but such fiber is considered inferior to that derived from Corchorus capsularis. Jute is the name of the plant or fiber used to make burlap, hessian, or gunny cloth. Jute is one of the most affordable natural fibers and second only to cotton in the amount produced and variety of uses. Jute fibers are composed primarily of the plant materials cellulose and lignin.""",
        'jute-cult' : """The jute plants are cut to the ground and tied into bundles. After that, sheaves of jute stocks are immersed in floodwater or ponds or stagnant water for about 2 - 3 weeks for retting. The high temperature of the water is advised which quickens the process of retting. Once retting is done, the bark is peeled from the plant & fibre is removed. Then comes stripping, rinsing, washing and cleaning. After that, the fibre is dried in the sun and pressed into bales. Remember all this process has to be done by human hand. Thus, the availability of more labour at cheap rates is very important. But the interesting part is there is no labour shortage as jute is cultivated in areas of high population density.""",
        'jute-climate' : """The suitable climate for growing jute is a warm and wet climate, which is offered by the monsoon climate during the fall season, immediately followed by summer. Temperatures ranging to more than 25 °C and relative humidity of 70%–90% are favorable for successful cultivation.""",
        

        'kidneybeans-sc-name' : """Phaseolus vulgaris""",
        'kidneybeans-desc' : """Common kidney beans—also known as red kidney beans—are large, kidney-shaped legumes that grow on bean bushes or poles from the common snap bean plant Phaseolus vulgaris. When they are cooked, kidney beans taste slightly sweet with a tender and grainy texture. Kidney beans contain nutrients like folate, magnesium, potassium, protein, and fiber. They are often used in chili, dips, as well as Indian, Middle Eastern, Central American, and Caribbean cuisines.""",
        'kidneybeans-cult' : """Purchase kidney bean seeds to plant in the ground. Rather than transplanting the plants, you want to grow them from seedlings. Bush beans and pole beans sprout from the same kinds of seeds. Choose a sunny spot in your garden. Kidney beans will need at least six hours of full sun a day for proper growth. Prepare your soil. You want to have loose, well-draining soil with a pH between 6.0 and 7.0 because the beans don’t respond well to high levels of moisture.Dig your holes. If you’re planting pole beans, create a series of one-to-two-inch deep holes, spacing them about four to six inches apart. If you’re planting bush beans, plant your seeds at least six inches apart, also at a depth of one-to-two-inches. If you’re cultivating a small bush in a planter, dig a single one-to-two inch hole in the middle of your planter. Direct sow your seeds. Like green beans and black beans, kidney beans have shallow roots, so it’s best to sow them directly into your soil rather than starting them in containers and transplanting them later. Water your bean seeds. Water your bean seeds whenever the soil around your plant appears dry. Overwatering can lead your seeds to rot.""",
        'kidneybeans-climate' : """Kidney beans are planted at the very beginning of spring—after the last frost of winter has passed—as they grow best in warm temperatures. When you start growing your beans, the air temperature should be around 65 degrees Fahrenheit, and the soil temperature should be at least 70 to 80 degrees Fahrenheit.""",


        'lentil-sc-name': """Lens culinaris""",
        'lentil-desc': """Lentils are a hardy annual; they are a member of the pea family. Lentils grow on sparsely branched vines from 18 to 24 inches tall. The lentil has small whitish to light purple pea-like flowers. Pods are small, broad, flat and contain one or two flat, a lens-shaped seed that is green or yellow to orange, red or brown. Lentils flower from the lower branches up until harvest. Each flower produces a short pod that contains two seeds.""",
        'lentil-cult': """Sow lentil seeds 1 t0 1½ inch deep, deeper if the soil is dry. Space seeds 1 inch apart. Innoculate lentil seeds before planting with Rhizobium leguminosarum. Thin successful seedlings to 4 to 5 inches apart. Space rows 18 to 24 inches apart. A target population per acre is 400,000 plants.""",
        'lentil-climate' : """Lentil requires cold climate. It is very hardy and can tolerate frost and severe winter to a great extent. It require cold temperature during its vegetative growth and warm temperature at the time of maturity. The optimum temperature for growth is 18-30°C.""",

        'maize-sc-name' : """Zea mays""",
        'maize-desc' : """Maize or Indian corn (Fig. 221) is a stout annual plant culti­vated for the grains during the rainy season. It forms a staple food in some parts of India. Roots are of fibrous adventitious type. Pri­mary root aborts after germination, and is replaced by fibrous adven­titious ones from the base of stem. Stems are stout, solid with distinct nodes and internodes. Leaves are simple with entire margin, quite large, linear in shape and arranged alternately. The arrange­ment is distichous or 2-ranked. They have sheathing leaf-base surrounding a part of internode above. Membranous ligule is present at the junction of base and blade. Venation is parallel. All the organs have rough surface due to impregnation of silica. Inflorescences are of two types, viz. terminal staminate compound raceme or panicle and axillary pistillate spadix.""",
        'maize-cult' : """Maize is sown in rows, 60-75 cm apart, whereas the plants in the row are spaced at 20 to 25 cm. A population of 60-75 thousand plants per hectare at harvest are required for obtaining the optimum yield. Sowing in rows is generally done with drill or by dropping the seed behind the plough. The practice of broading, particularly under rain fed conditions and for fodder maize is still prevalent in several parts of country. Seventeen to 20 kg of seed for the grain crop and 35-40 kg per hectare for the fodder crop is needed.""",
        'maize-climate' : """In India, maize is traditionally grown in monsoon (Kharif) season, which is accompanied by high temperature (<35° C) and rainfall. However, with the development of new cultivars and appropriate production technology, winter cultivation of maize has emerged as a viable alternative.""",


        'mango-sc-name' : """Mangifera indica""",
        'mango-desc' : """A mango is an edible stone fruit produced by the tropical tree Mangifera indica. It is believed to have originated in the region between northwestern Myanmar, Bangladesh, and northeastern India. Mango trees grow to 30–40 metres (98–131 feet) tall, with a crown radius of 10–15 m (33–49 ft). The trees are long-lived, as some specimens still fruit after 300 years. In deep soil, the taproot descends to a depth of 6 m (20 ft), with profuse, wide-spreading feeder roots and anchor roots penetrating deeply into the soil. The ripe fruit varies according to cultivar in size, shape, color, sweetness, and eating quality. The fruit has a single flat, oblong pit that can be fibrous or hairy on the surface, and does not separate easily from the pulp.""",
        'mango-cult' : """Prepare the site by digging a hole that is twice as wide and deep as the root ball. Check the drainage by filling the hole with water and watching how fast it drains. Mango trees can survive some periods of flooding, but the healthiest plants are produced where soils percolate well. Plant the young tree with the graft scar just at the soil surface. You don’t need to prune the young plant, but watch for suckers from the graft and prune them off. Young mango tree care must include frequent watering as the plant establishes. Mango trees grow easily from seed. Get a fresh mango pit and slit the hard husk. Remove the seed inside and plant it in seed starter mix in a large pot. Situating the seed with ¼-inch (.6 cm.) protruding above the soil surface works best for growing mango trees. Keep the soil evenly moist and place the pot where temperatures remain at least 70 F. (21 C.). Sprouting may occur as early as eight to 14 days, but may take up to three weeks. Keep in mind that your new mango tree seedling will not produce fruit for at least six years.""",
        'mango-climate' : """Mango trees require consistent warm temperatures. They don't tolerate long-term frost or cold conditions. If temperatures drop below 40 degrees F, even for short periods, the cold may kill both flowers and small fruits. Mature trees may be more capable of surviving colder temperatures, as low as 25 degrees F, but only for brief periods. Young trees are likely to suffer severe damage any time temperatures drop below 30 degrees, even if only briefly.""",

        
        'mothbeans-sc-name' : """Vigna aconitifolia""",
        'mothbeans-desc' : """Moth bean is a creeping annual herbaceous plant which grows to approximately 40 cm high. Yellow flowers on its hairy and densely packed branches develop into yellow-brown pods, 2 to 3 inches in length. The seeds of these pods contain approximately 22–24% protein. Belonging to the family Fabaceae (subfamily Papilionaceae), the moth bean is an herbaceous creeping annual that creates a low-lying soil cover when fully grown. Its stem can grow up to 40 cm in height, with its hairy and dense-packed branches reaching a span of up to 150 cm. Yellow flowers develop into a brown pod 2.5 to 5 cm in length, which holds 4 to 9 seeds inside.""",
        'mothbeans-cult' : """The moth bean can be grown both as single crop and forage crop. You will need about 10-20 kg seeds per hectare when grown as the only crop. And 7-34 kg seeds per hectare when the moth beans are grown as a forage crop. The moth bean seeds are generally shown in rows which are generally 1-3 feet apart. And sow the seeds to about 3-4 inches apart and to 1/2 to 1 inch deep. Watering slightly after sowing the seeds will ensure good germination of the seeds.""",
        'mothbeans-climate' : """Generally very little irrigation is required for growing moth bean plants. And moth bean is one of the most drought-resistant pulse in India. Ideal temperature for growing moth bean is between 24 °C and 32 °C. But the plants can also tolerate up to 45 °C during the day. Ideal annual rainfall for growing moth bean plants is between 500 and 750 mm (but the plants can also do well with 300 mm annual rainfall).""",

        'mungbean-sc-name' : """Vigna radiata""",
        'mungbean-desc' : """The mung bean (Vigna radiata (L.) R. Wilczek) is a legume cultivated for its edible seeds and sprouts across Asia. The mung bean plant is an annual, erect or semi-erect, reaching a height of 0.15-1.25 m. The leaves are alternate, trifoliolate with elliptical to ovate leaflets, 5-18 cm long x 3-15 cm broad. The flowers (4-30) are papillonaceous, pale yellow or greenish in colour. The pods are long, cylindrical, hairy and pending. They contain 7 to 20 small, ellipsoid or cube-shaped seeds. The seeds are variable in colour: they are usually green, but can also be yellow, olive, brown, purplish brown or black, mottled and/or ridged. Seed colours and presence or absence of a rough layer are used to distinguish different types of mung bean.""",
        'mungbean-cult' : """Planting mung beans is simple and begins with adding 1-2 inches of compost to the soil. Since mung beans are nitrogen-fixing, they won’t require much nitrogen fertilizer. A few inches of composted organic matter that is nutrient-rich should be enough to feed the entire plant throughout its lifespan. To start to grow mung beans, plant seeds one inch deep into the soil and two inches away from each other. The rows should be 30-36 inches apart. Add a bean inoculant into the hole or apply it to the seed directly. Inoculants are optional, but they help the beans create nitrogen more efficiently.""",
        'mungbean-climate' : """Mungbean grows in a wide range of climatic conditions. A warm humid climate with temperature ranging from 25⁰ C to 35⁰ C, with 400-550 mm rainfall, well distributed during the growing period of 60 - 90 days, is suitable for cultivation.""",

        
        'muskmelon-sc-name' : """Cucumis melo""",
        'muskmelon-desc' : """Muskmelons are among the most-important commercial melons and are commonly eaten fresh. Although the term muskmelon is sometimes loosely applied to any dessert melon, in botanical usage it refers strictly to the fruits that are cultivars of the common melon (Cucumis melo) and are classified in the Reticulatus cultivar group. In addition, those melons are sometimes inaccurately referred to as cantaloupe in North America, a term that should properly be reserved for European melons of the Cantalupensis group. Like all melons, muskmelons are annual vines that require a long warm growing season. They have hairy trailing stems with clasping tendrils and bear round to lobed leaves. The yellow unisexual flowers produce large fruits, which give off a sweet odour when ripe. The plants are susceptible to a number of fungal diseases, especially in humid conditions, and are killed by frost.""",
        'muskmelon-cult' : """Sow seeds 1 inch deep in rows, or in hills spaced 6 feet apart. After 2 weeks, thin to 2 plants per hill. To prevent insect problems and encourage early growth, cover seedlings with row cover (fleece) tunnels until they begin to bloom. They are often grown in widely spaced enriched hills, or in well-aged compost heaps that include some soil.""",
        'muskmelon-climate' : """Muskmelon plant flourishes well under warm climate and cannot tolerate frost. The optimum temperature for germination of the seed is 27 degree Celsius - 30 degree Celsius with an increase in temperature.""",

       
        'papaya-sc-name' : """Carica papaya""",
        'papaya-desc' : """The papaya plant is considered a tree, though its palmlike trunk, up to 8 metres (26 feet) tall, is not as woody as the designation generally implies. The plant is crowned by deeply lobed leaves, sometimes 60 cm (2 feet) across, borne on hollow petioles (leaf stalks) 60 cm long. Normally, the species is dioecious, male and female flowers being produced on separate plants, but hermaphroditic forms are known, and numerous irregularities in the distribution of the sexes are common. Male flowers are borne in clusters on stalks 90 cm long; the flowers are funnel-shaped, about 2.5 mm (0.1 inch) long, and whitish, with 10 stamens in the throat. The female flowers are considerably larger, on very short stalks, and often solitary in the leaf axils; they have five fleshy petals that are united toward the base and a large cylindrical or globose superior ovary that is crowned by five fan-shaped sessile stigmas.""",
        'papaya-cult' : """Papayas are usually grown from seed. Their development is rapid, with fruit being produced before the end of the first year. Under favourable conditions, a plant may live five years or more. The papaya ringspot virus nearly wiped out papaya crops around the world, first hitting Hawaiian plantations in the 1940s and soon spreading. A genetically modified (GMO) variety named the Rainbow papaya was developed in the early 2000s with resistance to the virus. It was one of the first GMO fruits in commercial production, and the majority of exported papayas are now GMO crops.""",
        'papaya-climate' : """Papaya thrives best under warm, humid conditions. It is generally intolerant of strong winds and cold weather. Temperatures just below freezing can kill small plants to the ground–larger plants that are not killed outright will normally produce suckers to regenerate the plant and bear fruit within a year.""",

        
        'grapes-sc-name' : """Vitis""",
        'grapes-desc' : """Grapes are a type of fruit that grow in clusters of 15 to 300, and can be crimson, black, dark blue, yellow, green, orange, and pink. 'White' grapes are actually green in color, and are evolutionarily derived from the purple grape. Mutations in two regulatory genes of white grapes turn off production of anthocyanins, which are responsible for the color of purple grapes. Anthocyanins and other pigment chemicals of the larger family of polyphenols in purple grapes are responsible for the varying shades of purple in red wines. Grapes are typically an ellipsoid shape resembling a prolate spheroid.""",
        'grapes-cult' : """Before planting bare root vines, soak the roots in water for 3-4 hours. At planting, remove all canes except the most vigorous one. Plant vines with the lowest bud on the cane just above the soil surface. Trim off any broken or excessively long roots. Dig a hole large enough to you can spread the root system out.  Then cover the roots completely with soil.After planting, water the vines regularly throughout the first year. The root system needs to grow and establish to allow for shoot growth in the first year. Grapevines need some type of support or they will trail along the ground. The support can be an arbor covering a patio for shade, or can be as simple as a post in the ground to support the trunk of the vine.""",
        'grapes-climate' : """Adequate sun, heat, and water during the growing season, and enough cold during the dormancy phase are crucial for healthy growth of vines and production of premium quality grapes. Grapevines thrive best in climates with long warm summers, and rainy winters. Warm weather during the growing period enables grapevine to flower, fruit set and ripen. On average, grapevines require temperatures above 10°C (50°F)) in order to ripe properly, depending on the growing region and vine variety. Grapevines also need water in order to thrive. In some areas and climates, there is more than enough rain for the vines to survive, while in other regions, vines needs to be irrigated. How much water grapevines need depends on several factors, such as climate, heat, soil, wine variety, etc. Apart from already mentioned climatic factors, also wind, humidity, atmospheric pressure, and sunlight have effect on grape growth.""",

  
        'orange-sc-name' : """Citrus sinensis""",
        'orange-desc' : """An orange is a fruit of various citrus species in the family Rutaceae; it primarily refers to Citrus sinensis, which is also called sweet orange, to distinguish it from the related Citrus aurantium, referred to as bitter orange. The sweet orange reproduces asexually (apomixis through nucellar embryony); varieties of sweet orange arise through mutations. The orange originated in a region encompassing Southern China, Northeast India, and Myanmar. Orange trees are widely grown in tropical and subtropical climates for their sweet fruit. The fruit of the orange tree can be eaten fresh, or processed for its juice or fragrant peel.""",
        'orange-cult' : """Dig pits at 75 cm x 75 cm x 75 cm size at 7 x 7 m spacing. Fill up the pits with top soil and 10 kg of FYM. Plant the budded plants in the centre of the pits and stake it. Immediately after planting irrigate copiously. Irrigations may be given once in 10 days. Avoid water stagnation near the plant during monsoon and cyclone periods. Nitrogen has to be applied in two doses during March and October. However Farm yard manure, Phosphorous and Potash are to be applied in October. As intercultural operations remove the water shoots, rootstock sprouts, dead and diseased shoots. For higher productivity remove all the laterals upto 45 cm from ground level.""",
        'orange-climate' : """Orange trees are widely grown in tropical and subtropical climates for their sweet fruit. The fruit of the orange tree can be eaten fresh, or processed for its juice or fragrant peel.The ideal season for cultivation of sweet orange is July to September.""",

       
        'banana-sc-name' : """Musa sp.""",
        'banana-desc' : """A banana is an elongated, edible fruit – botanically a berry – produced by several kinds of large herbaceous flowering plants in the genus Musa. In some countries, bananas used for cooking may be called 'plantains', distinguishing them from dessert bananas. The fruit is variable in size, color, and firmness, but is usually elongated and curved, with soft flesh rich in starch covered with a rind, which may be green, yellow, red, purple, or brown when ripe. The fruits grow upward in clusters near the top of the plant. Almost all modern edible seedless (parthenocarp) bananas come from two wild species – Musa acuminata and Musa balbisiana. The scientific names of most cultivated bananas are Musa acuminata, Musa balbisiana, and Musa paradisiaca for the hybrid Musa acuminata M. balbisiana, depending on their genomic constitution. The old scientific name for this hybrid, Musa sapientum, is no longer used.""",
        'banana-cult' : """For the plantation of Banana, about 70% of the farmers are using suckers as planting material while the rest 30% of the farmers are using tissue culture seedlings. Sword suckers with well developed rhizome, conical or spherical in shape having actively growing conical bud and weighing approximately 450-700 gm are commonly used as propagating material.The roots and base of the planting material may be removed. The suckers are dipped in a solution of 0.5 % monocrotophos and bavistin (0.1%) before planting.Planting of tissue culture banana can be done throughout the year as per the market demand except when the temperature is too low or too high. The planting time may be adjusted so as to avoid high temperature and drought at the time of emergence of bunches (i.e. approx. 7-8 months after planting). The planting time for long duration cultivars is different from short duration ones.""",
        'banana-climate' : """Banana grows well in a temperature range of 15ºC – 35ºC with relative humidity of 75-85%. It prefers tropical humid lowlands and is grown from the sea level to an elevation of 2000m. Chilling injury occurs at temperature below 12ºC. Four months of monsoon (June to September) with an average 650-750 mm rainfall are most important for vigorous vegetative growth of banana. At higher altitudes, banana cultivation is restricted to a few varieties like ‘Hill banana”.""",

  
        'pigeonpeas-sc-name' : """Cajanus cajan""",
        'pigeonpeas-desc' : """Pigeon pea is an erect, short-lived perennial leguminous shrub that usually grows to a height of about 1-2 m, but can reach up to 2-5 m high. It quickly develops a deep (2 m depth) poisonous taproot. The stems are woody at the base, angular and branching. The leaves are alternate and trifoliate. The leaflets are oblong and lanceolate, 5-10 cm long x 2-4 cm wide. Leaves and stems are pubescent. The flowers (5 to 10) are grouped in racemes at the apices or axils of the branches. The flowers are papilionaceous and generally yellow in colour. They can also be striated with purple streaks. The corolla is about 2-2.5 cm. The fruit is a flat, straight and pubescent pod, 5-9 cm long x 12-13 mm wide. It contains 2-9 seeds that are brown, red or black in colour, small and sometimes hard-coated.""",
        'pigeonpeas-cult' : """It grows on variety of soil. It gives best result on fertile and well drained loamy soils. The saline-alkaline or waterlogged soils are unfit for its cultivation. It can grow successfully on soils having pH ranges from 6.5 to 7.5.Prepared land by taking one deep ploughing followed by two or three times harrowing. Planking should be followed after each ploughing. It cannot withstand in water logging conditions, prepared field in such a way that water stagnation should not take place. Crop Rotation: Follow crop rotation of Arhar with Wheat or Barley or Sufed Senji or Sugarcane.For good yield use seed rate of 6 kg per acre.""",
        'pigeonpeas-climate' : """Pigeon pea grows well in worm tropical and subtropical climate. The crop prefers a fairly moist and warm climate during the period of its vegetative growth during the flowering and repining stages of its growth, its requires bright sunny weather for the setting of fruits. It is highly susceptible to frost at the time of flowering. Cloudy weather and excessive rainfall at flowering time damage the crop to great extent.""",


        'pomegranate-sc-name' : """Punica granatum""",
        'pomegranate-desc': """ Pomegranate, Punica granatum, is a deciduous or evergreen tree or shrub in the family Punicaceae grown for its edible fruits. The pomegranate tree is branched and spiny with glossy, leathery, oval to oblong leaves that grow in whorls of five or more on the branches. The tree produces bright red flowers singly at the tips of the branches and a rounded hexagonal fruit with a thick pink-red skin. The fruit has a thick, leathery rind which protects the pulp[ and seeds inside. The inside of the fruit is separated into compartments by white spongy tissue. Each compartment contains seeds and pulp. Each pomegranate fruit may contain as many as 600 seeds. Pomegranate trees can reach a height of 10 m (33 ft) and can be very long lived, although their economic lifespan is usually between 12 and 15 years. Pomegranate may also be referred to as grenadine or Chinese apple and originated from Central Asia, likely in Iran.""",
        'pomegranate-cult' : """Pomegranate is propagated vegetatively by cuttings, air layering or gootee. Square system of planting is mostly adopted. Planting distance is decided on the basis of soil type and climate. A spacing of 4-5 m. on marginal and very light soils is recommended. Pits of 60 X 60 X 60 cm. size are dug (at a spacing of 5 cm. in square system) about a month prior to planting and kept open under the sun for a fortnight. About 50 g. of 5% BHC or carbaryl dust is dusted on the bottom and sides of the pits as a pre-caution against termites. The pits are filled with top soil mixed with 20 kg. farmyard manure and 1 kg. super phosphate. After filling the pit, watering is done to allow soil to settle down. Cuttings/air layers are then planted and staked. Irrigation is provided immediately after planting.""",
        'pomegranate-climate' : """Pomegranate grows well under semi-arid conditions and can be grown upto an altitude of 500 m. above m.s.l.. It thrives well under hot, dry summer and cold winter provided irrigation facilities are available. The tree requires hot and dry climate during fruit development and ripening.""",

	
	'watermelon-sc-name' : """Citrullus lanatus""",
        'watermelon-desc' : """The watermelon is a crawling and climbing plant with lengthy stems and leaves divided in lobes. Its fruit is a berry that may weigh up to 15kg, with a hard green rind and a sweet pulp of more or less reddish colour. The watermelon is an annual plant that belongs to the family of Cucurbitaceous. Its scientific name is Citrullus vulgaris. It has some herbaceous stems that may reach 5m of length. They are cylindrical, with longitudinal and hairy furrows. The upper side of the leaves is very smooth, whereas the reverse is very rough, with strongly marked nerves. The leaves are divided in rounded segments, each one with 3 to 5 lobes. The flowers are born in the axils of the leaves. They are yellow and solitary, masculine and feminine.""",
	'watermelon-cult' : """Watermelons need soil that is well-drained and sandy. They also need a pH level between 6.0 and 6.5, a very narrow range. Test your soil before adding any compost or fertilizer to know if you need to add any nutrients and in what amounts, and water your watermelon plants regularly when they're young. Typically, watermelon plants need 1-2 inches of water per week so that the soil stays moist but not wet. If you're not getting enough rain each week, make sure you give your plants an extra drink.To suppress weeds and keep soil moist, apply a 1- to 2-inch layer of organic mulch around watermelon vines when they reach 6 to 8 inches long. Frequently hand-pull weeds when they're small; if you wait until weeds are large, the weeds' large root systems could disturb a watermelon's shallow roots.""",
        'watermelon-climate' : """The best average temperature range for watermelon production during the growing season is between 65°F and 95°F. Temperatures above 95°F or below 50°F will slow the growth and maturation of the crop. Watermelons require a constant supply of moisture during the growing season.""",

        'dhekia-sc-name' : """Blechnum orientale""",
        'dhekia-desc': """Dhekia are terrestrial herb with erect, thick, massive rhizome, 20-30 x 15-18 cm. They are scaly beneath, glabrous above; lamina simply pinnate. The plants are grooved above, rounded below; veins close, forked, almost perpendicular to the costa.""",
        'dhekia-cult' : """The perennials prefer a half-shady to shady situation on moist soil. The substrate should be sandy loam or sandy clay with a pH between 4 and 6.The plants should be grown in semi-shade if cultivated outdoors.""",
        'dhekia-climate' : """Dhekia grows in sunny places near hill slopes. It grows in areas that have partial shade to full shade. This species suited to tropical or subtropical climates.""",


        'kolakosu-sc-name' : """Colocasia esculenta""",
        'kolakosu-desc':"""Kola kosu leaves are the heart-shaped leaves of the taro plant (Colocasia esculenta), commonly grown in subtropical and tropical regions.While generally known for its edible, starchy root, the leaves of the taro plant also serve as a staple food in various cuisines.While consuming cooked taro leaves may offer some health benefits, it’s important to note that the raw leaves are poisonous before cooking.""",
        'kolakosu-cult' : """Colocasia needs plenty of warmth, humidity and moist soil to thrive. Outside, grow in dappled shade, in moist, rich soil in a sheltered spot and bring back indoors in autumn. If growing as a house plant, give it bright but indirect light and a humid atmosphere.""",
        'kolakosu-climate' : """It comes up well in loamy soils with a pH range of 5.5-7.0 and a combination of warm and moist climate with a mean temperature of 21-270 C. It can be grown up to 1500 m elevation with well distributed rainfall of about 1000 mm during growth period.""",

        'suhonibon-sc-name': """Spilenthes acmella""",
        'suhonibon-desc': """Spilanthes acmella(suhonibon) is an important medicinal plant, found in tropical and subtropical countries mainly India and South America. Popularly, it is known as toothache plant which reduces the pain associated with toothaches and can induce saliva secretion. Various extracts and active metabolites from various parts of this plant possess useful pharmacological activities.""",
        'suhonibon-cult' : """The optimal temperature for germinating the seeds is 20-24°C (68-75°F). It is important to sow the seeds by burrowing them to about only 1/4 inch deep as they require light to stimulate germination. Germination takes approximately 1-2 weeks. For the best germination results, it is recommended to grow indoors in sterilized potting soil. A black earth and peat moss mixture works well. Always keep soil moist but never soggy. Once the seedlings have at least 2 sets of leaves they can be transplanted when the danger of frost has passed.""",
        'suhonibon-climate' : """Afternoon shade in hot summer areas is ok. Plant spilanthes transplants 6 to 12 inches apart. Toothache plant grows about 12 inches tall and 12 to 18 inches wide. To plant toothache plant from seed in the spring, sprinkle 2-3 seeds on top of soil every 6 inches.""",

        'aibika-sc-name' : """Abelmoschus manihot""",
        'aibika-desc' : """Abelmoschus manihot, the aibika, is a flowering plant in the family Malvaceae. It was formerly considered a species of Hibiscus, but is now classified in the genus Abelmoschus. The plant is also known as the sunset muskmallow, sunset hibiscus, or hibiscus manihot. Although technically a shrub, aibika is a perennial which, under good conditions, can grow to over three meters in height. It is reputedly an extremely nutritious vegetable.""",
        'aibika-cult' : """Cuttings are best taken when the soil temperature is at least 25°C. It is easily propagated from cuttings 10 - 20 cm long, half buried in potting mix and kept moist. Space plants at 60 cm apart.""",
        'aibika-climate' : """Abelmoschus manihot thrive in full sun in fertile, moist, well drained soil. They need regular fertilization, and irritation for best performance.""",

        'latumoni-sc-name' : """Abrus precatorius""",
        'latumoni-desc' : """Abrus precatorius, commonly known as jequirity bean or rosary pea, is a herbaceous flowering plant in the bean family Fabaceae. It is a slender, perennial climber with long, pinnate-leafleted leaves that twines around trees, shrubs, and hedges. The plant is best known for its seeds, which are used as beads and in percussion instruments, and which are toxic because of the presence of abrin. Abrus precatorius is a severely invasive plant in warm temperate to tropical regions, so much so that it has become effectively pantropical in distribution.""",
        'latumoni-cult' : """Propagation is by scarified seed sown in spring. Abrus precatorius seeds germinate more successfully if scarified.The seeds is coverd with very hot water and soak overnight or until they swell. Pick out those that didn't swell and repeat process with them. The swollen seeds is immediately sown in seeding mix, covering with two to three times their thickness. Overwater or too much dryness should be checked and provide good drainage and bright light to the plant. The plant should germinate within a few weeks with pretreatment or erratically without.""",
        'latumoni-climate' : """Abrus precatorius plants are seen growing wild throughout all tropical forests, and are propagated through seeds. Abrus precatorius is adaptable to most soils, but prefers a tropical climate with reasonably high rainfall and a sunny position. A. precatorius grows in subtropical moist forest (1000 to 2000 mm of precipitation), and subtropical dry forest (below 1000 mm of precipitation), and prefers well-drained soil but can tolerate most types. In India, all types of topography are colonized from near sea level to 1000 m in elevation (Parrotta, 2001). """

    }
